version: '3'
services:
    mongodb:
        image: mongo
        container_name: mongodb
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017

    mongoclient:
        image: mongoclient/mongoclient
        container_name: mongoclient
        depends_on:
            - mongodb              
        environment:
            - MONGO_URL=mongodb://mongodb
        volumes:
            - mongoclient:/data/db

        ports:
            - '3000:3000'

volumes:
  mongodb:
  mongodb_config:
  mongoclient: