version: '3'
services:
    rabbitmq:
        image: 'rabbitmq:3-management-alpine'
        container_name: rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
  
    rabbit1:
        image: 'rabbitmq:3-management'
        hostname: rabbit1
        ports:
            - '15672:15672'
            - '5672:5672'
        labels:
        NAME: rabbitmq1